### ISSUE TITLE
Todo steps after parse

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#3]
Hey @jods4,

As we now have a nice parser, besides optimizing the parser and implementing more features, I think the the steps will be:
- [x] 1. Parse template (the parser)
- [x] 2. Optimize parse result
- [ ] 3. Cache (the optimized result)
- [x] 4. Render
- [ ] 5. Object serialize ("dump")

An example for 2. is combining two textparts to one: `"{{a"` will have now two parts, "{" and "a". 

Do you think 2. should be a separate step, or merged with the parse step (1)?

**Comment by jods4** [comment]
About 2., I think it's cleaner to do a post-processing pass. 
I'd argue that (a) escaped strings are uncommon, (b) there's little to win in term of memory allocations trying to grab `abc{{def` at once, (c) it's a one-time thing that's going to be cached. 
So my opinion is: let's go for the cleanest / simplest code.
BTW: a post processing pass is probably required anyway for other things, like determining if all indexes are numbers: `{0} {1} {2}` vs `{0} {a} {1}`. The latter is valid but handled very differently.

About 3., I think it would be interesting to cache templates based their reference rather than string hash. 
Because the typical pattern is: `logger.Log("Request completes in {time}ms", time)`, which mean the string _reference_ will always be the same.
Naively using `var cache = new Dictionary<string, PartList>()` would hash strings, which is of course slower.

Of course it implies that `logger.Log(what + " completes in {time}ms", time)` would be parsed every time, but I'm not worried because it's an anti-pattern and parsing is fast anyway. I prefer to optimize for the common/correct case.

Only caveat: how to avoid the cache from overflowing of one-time strings?

**Comment by 304NotModified** [comment]
> About 2., I think it's cleaner to do a post-processing pass. 
> I'd argue that (a) escaped strings are uncommon, (b) there's little to win in term of memory allocations

So if it's uncommon (I also think that), then we could skip this optimize-step.

> BTW: a post processing pass is probably required anyway for other things, like determining if all indexes are numbers: {0} {1} {2} vs {0} {a} {1}. The latter is valid but handled very differently.

Yes indeed. We need to check if all parameters are numbers (could be partly in step 1)

> About 3., I think it would be interesting to cache templates based their reference rather than string hash.

Good idea! But is it this possible without `unsafe`? 

> Only caveat: how to avoid the cache from overflowing of one-time strings?

Maybe keep that cache a logger level, although the recommendation is to create a `static` logger.

**Comment by jods4** [comment]
> Good idea! But it this possible without unsafe?

It is. You can create an `IEqualityComparer<string>` based upon `Object.ReferenceEquals()` and `RuntimeHelpers.GetHashCode()`. 
The latter always calls `Object.GetHashCode()`, no virtual dispatch.

**Comment by 304NotModified** [comment]
Nice !

**Comment by 304NotModified** [comment]
IMO the optimize parse result is done, nice work @jods4 !

**Comment by jods4** [comment]
@304NotModified Thanks :)
Note that the parser still doesn't process escaped format strings properly.

**Comment by 304NotModified** [comment]
Could you give an example what goes wrong?

**Comment by jods4** [comment]
Here are some quirks that may surprise you:

``` c#
string.Format("{{{0:d}}}", 3) == "{d}"
string.Fomrat("{{{0:0{{}", 3) == "{3{"
```

**Comment by 304NotModified** [comment]
that's indeed surprising!

**Comment by 304NotModified** [comment]
@jods4 https://github.com/NLog/yamtp/pull/24 the parser works?

**Comment by 304NotModified** [comment]
Mmmm don't get it

![image](https://cloud.githubusercontent.com/assets/5808377/17715852/5d9ea692-6406-11e6-9fa6-35ba6e675638.png)

![image](https://cloud.githubusercontent.com/assets/5808377/17715867/738e2ad6-6406-11e6-92fe-a1fda041da46.png)

**Comment by jods4** [comment]
@304NotModified 

> @jods4 #24 the parser works?

See my comment over there. No it doesn't. It does parse and rebuilds the same string, yet it does not parse _correctly_. Rendering will be incorrect.

Explanations
The escaped opening braces are irrelevant, but they lure you into wrong expectations.
Braces are parsed left to right, double braces are considered an escape no matter where they appear.
`{{{d}}}`, let's parse this!
- `{{` escaped `{`.
- `{` open hole
- `d` 
- `}}` escaped `}`, so format is `d}`.
- `}` close hole.

And because `d}` is not a standard format it is interpreted as a custom format string. For ints, this is all literal stuff, so we end up with `{d}`.

Do the same for `{{{0{{}`. We end up with `0{` custom format, applied to 3 the result is `{3{`.

**Comment by 304NotModified** [comment]
thanks!

LOL don't understand why it has this behavior, sounds just more complicated for the parser. Well they need probably `}` in formats..

**Comment by 304NotModified** [comment]
working on it

**Comment by 304NotModified** [comment]
https://github.com/NLog/yamtp/pull/25

But the code is not the best ;)

**Comment by 304NotModified** [comment]
5)  Object serialize ("dump") => will be JSON

**Comment by 304NotModified** [comment]
3)  moved to https://github.com/NLog/NLog.StructuredEvents/issues/31
